
spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "v2"

accounts:
  message: "welcome to Accounts loans to quality apis "
  contactDetails:
    email: "aditya@gmail.com"
    mobileNumber: "1234567890"
  callSupport:
    - "aditya@gmail.com"
    - "1234567890"
